[Scaffold.project]
name = "perlin-noise"
version = "0.1.0"
language = C
c_standard = C11
target_type = EXECUTABLE

[Scaffold.deps]
templates = "sdl2"
; system_packages = OpenGL

; [[Scaffold.deps.github]]
; url = "https://github.com/aikoschurmann/cfgsafe"
; tag = "main"
; target = "cfgsafe"
; options = ""

[Scaffold.testing]
enabled = true
framework = UNITY

[Scaffold.tooling]
use_clang_format = true
use_asan = false
use_cfgsafe = true
format_style = LLVM

[Scaffold.meta]
author = "aiko schurmann"
email = "aiko.schurmann@gmail.com"
license = MIT
init_git = true
