/* Generated by cfg-gen for /Users/aikoschurmann/code/c/perlin-noise-map/schemas/app.cfgsafe */
#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdio.h>
#include <string.h>
#include <stdbool.h>
#include <stdint.h>

typedef enum {
    CFG_SUCCESS = 0,
    CFG_ERR_OPEN_FILE,
    CFG_ERR_SYNTAX,
    CFG_ERR_VALIDATION,
} cfg_status_t;

typedef struct {
    char message[512];
    char field[256];
    size_t line;
} cfg_error_t;

static inline void cfg_set_error(cfg_error_t *err, const char *msg, const char *field, size_t line) {
    if (!err) return;
    if (msg) { strncpy(err->message, msg, sizeof(err->message) - 1); err->message[sizeof(err->message) - 1] = '\0'; }
    if (field) { strncpy(err->field, field, sizeof(err->field) - 1); err->field[sizeof(err->field) - 1] = '\0'; }
    err->line = line;
}


typedef struct AppConfig_t AppConfig_t;

typedef struct Window_t {
    const char* title;
    int64_t width;
    int64_t height;
} Window_t;

struct AppConfig_t {
    Window_t Window;
    void* internal_pool;
};

cfg_status_t AppConfig_load(AppConfig_t *cfg, const char *filename, int argc, const char **argv, cfg_error_t *err);
void AppConfig_parse_cli(AppConfig_t *cfg, int argc, const char **argv);
void AppConfig_print(const AppConfig_t *cfg, FILE *f);
void AppConfig_free(AppConfig_t *cfg);
bool AppConfig_validate(const AppConfig_t *cfg, cfg_error_t *err);
bool Window_validate(const Window_t *cfg, cfg_error_t *err);

#ifdef __cplusplus
}
#endif

#endif /* APP_CONFIG_H */

#ifdef CONFIG_IMPLEMENTATION

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
typedef struct cfg_pool_node {
    void *ptr;
    struct cfg_pool_node *next;
} cfg_pool_node_t;

static void* cfg_pool_alloc(cfg_pool_node_t **head, size_t size) {
    void *ptr = malloc(size);
    if (!ptr) return NULL;
    cfg_pool_node_t *node = (cfg_pool_node_t*)malloc(sizeof(cfg_pool_node_t));
    if (!node) { free(ptr); return NULL; }
    node->ptr = ptr;
    node->next = *head;
    *head = node;
    return ptr;
}

static void cfg_pool_free(cfg_pool_node_t *head) {
    while (head) {
        cfg_pool_node_t *next = head->next;
        free(head->ptr);
        free(head);
        head = next;
    }
}

typedef struct {
    void *cfg;
    cfg_pool_node_t *pool;
} cfg_common_context_t;

static char* cfg_next_token(char **str, const char *delim) {
    char *s = *str;
    if (!s || *s == '\0') return NULL;
    s += strspn(s, delim);
    if (*s == '\0') { *str = s; return NULL; }
    char *token = s;
    s += strcspn(s, delim);
    if (*s != '\0') { *s = '\0'; *str = s + 1; }
    else { *str = s; }
    return token;
}

static const char* cfg_intern_string(cfg_common_context_t *ctx, const char *s) {
    if (!s) return NULL;
    char *copy = (char*)cfg_pool_alloc(&ctx->pool, strlen(s) + 1);
    if (copy) strcpy(copy, s);
    return copy;
}

static void cfg_parse_array_string(cfg_common_context_t *ctx, const char *val, void **data, size_t *count) {
    char *val_copy = (char*)malloc(strlen(val) + 1);
    if (!val_copy) return;
    strcpy(val_copy, val);
    char *s = val_copy;
    char *token = cfg_next_token(&s, ",");
    size_t n = 0;
    while (token) { n++; token = cfg_next_token(&s, ","); }
    free(val_copy);
    *count = n;
    if (n == 0) { *data = NULL; return; }
    *data = cfg_pool_alloc(&ctx->pool, n * sizeof(const char*));
    val_copy = (char*)malloc(strlen(val) + 1);
    if (!val_copy) return;
    strcpy(val_copy, val);
    s = val_copy;
    token = cfg_next_token(&s, ",");
    for (size_t i = 0; i < n; i++) {
        while(isspace(*token)) token++;
        char *elem = token;
        if (*elem == '\"') {
            elem++;
            char *v_end = strrchr(elem, '\"');
            if (v_end) *v_end = '\0';
        } else {
            char *v_end = elem + strlen(elem) - 1;
            while(v_end > elem && isspace(*v_end)) *v_end-- = '\0';
        }
        ((const char**)*data)[i] = cfg_intern_string(ctx, elem);
        token = cfg_next_token(&s, ",");
    }
    free(val_copy);
}

static void cfg_parse_array_int(cfg_common_context_t *ctx, const char *val, void **data, size_t *count) {
    char *val_copy = (char*)malloc(strlen(val) + 1);
    if (!val_copy) return;
    strcpy(val_copy, val);
    char *s = val_copy;
    char *token = cfg_next_token(&s, ",");
    size_t n = 0;
    while (token) { n++; token = cfg_next_token(&s, ","); }
    free(val_copy);
    *count = n;
    if (n == 0) { *data = NULL; return; }
    *data = cfg_pool_alloc(&ctx->pool, n * sizeof(int64_t));
    val_copy = (char*)malloc(strlen(val) + 1);
    if (!val_copy) return;
    strcpy(val_copy, val);
    s = val_copy;
    token = cfg_next_token(&s, ",");
    for (size_t i = 0; i < n; i++) {
        ((int64_t*)*data)[i] = strtoll(token, NULL, 10);
        token = cfg_next_token(&s, ",");
    }
    free(val_copy);
}

typedef void (*cfg_ini_cb)(void *user, const char *sec, const char *key, const char *val);
static cfg_status_t cfg_parse_ini(const char *filename, cfg_ini_cb cb, void *user, cfg_error_t *err) {
    FILE *f = fopen(filename, "r"); if (!f) { cfg_set_error(err, "failed to open file", filename, 0); return CFG_ERR_OPEN_FILE; }
    char line[4096], section[256] = "";
    size_t line_num = 0; bool success = true;
    while (fgets(line, sizeof(line), f)) {
        line_num++; char *p = line; while(isspace(*p)) p++;
        if (*p == '\0' || *p == ';' || *p == '#') continue;
        if (*p == '[') {
            bool is_array = (*(p+1) == '[');
            if (is_array) p++;
            char *end = is_array ? strstr(p, "]]") : strchr(p, ']');
            if (end) {
                size_t len = end - (p + 1);
                if (len >= sizeof(section)) len = sizeof(section) - 1;
                strncpy(section, p + 1, len);
                section[len] = '\0';
                if (is_array) cb(user, section, NULL, NULL);
            } else { cfg_set_error(err, "missing closing bracket for section", section, line_num); success = false; }
        } else {
            char *eq = strchr(p, '=');
            if (eq) {
                *eq = '\0'; char *key = p, *val = eq + 1;
                char *k_end = key + strlen(key) - 1; while(k_end > key && isspace(*k_end)) *k_end-- = '\0';
                while(isspace(*val)) val++;
                
                // Handle quoted values and inline comments
                bool in_quotes = false;
                char *ptr = val;
                char *comment = NULL;
                while (*ptr) {
                    if (*ptr == '\"') in_quotes = !in_quotes;
                    else if ((*ptr == ';' || *ptr == '#') && !in_quotes) {
                        comment = ptr;
                        break;
                    }
                    ptr++;
                }
                if (comment) *comment = '\0';
                
                char *v_end = val + strlen(val) - 1;
                while(v_end >= val && isspace(*v_end)) *v_end-- = '\0';
                
                if (*val == '\"' && v_end >= val && *v_end == '\"') {
                    int quote_count = 0;
                    for (char *q = val; *q; q++) if (*q == '\"') quote_count++;
                    if (quote_count == 2) {
                        val++;
                        *v_end = '\0';
                    }
                }
                cb(user, section, key, val);
            } else {
                cfg_set_error(err, "missing assignment operator", p, line_num); success = false;
            }
        }
    }
    fclose(f);
    return success ? CFG_SUCCESS : CFG_ERR_SYNTAX;
}

bool AppConfig_validate(const AppConfig_t *cfg, cfg_error_t *err) {
    if (!cfg) return false;
    (void)err;
    if (!Window_validate(&cfg->Window, err)) return false;
    return true;
}

bool Window_validate(const Window_t *cfg, cfg_error_t *err) {
    if (!cfg) return false;
    (void)err;
    if (cfg->width < 320) { cfg_set_error(err, "value too small", "width", 0); return false; }
    if (cfg->width > 3840) { cfg_set_error(err, "value too large", "width", 0); return false; }
    if (cfg->height < 240) { cfg_set_error(err, "value too small", "height", 0); return false; }
    if (cfg->height > 2160) { cfg_set_error(err, "value too large", "height", 0); return false; }
    return true;
}

void AppConfig_print(const AppConfig_t *cfg, FILE *f) {
    if (!cfg) return;
    if (!f) f = stdout;
    fprintf(f, "--- AppConfig Configuration ---\n");
    fprintf(f, "%*s[Window]\n", 0, "");
    fprintf(f, "%*stitle = ", 2, "");
    fprintf(f, "\"%s\"\n", cfg->Window.title ? cfg->Window.title : "null");
    fprintf(f, "%*swidth = ", 2, "");
    fprintf(f, "%lld\n", (long long)cfg->Window.width);
    fprintf(f, "%*sheight = ", 2, "");
    fprintf(f, "%lld\n", (long long)cfg->Window.height);
    fprintf(f, "--------------------------\n");
}

static void AppConfig_ini_handler_recursive(cfg_common_context_t *ctx, const char *key, const char *val, char **parts, int num_parts, int depth) {
    (void)parts; (void)depth;
    if (num_parts == 0) {
    }
    if (0 < num_parts && strcmp(parts[0], "Window") == 0) {
        if (num_parts == 1) {
            if (strcmp(key, "title") == 0) {
                ((AppConfig_t*)ctx->cfg)->Window.title = cfg_intern_string(ctx, val);
                return;
            }
            if (strcmp(key, "width") == 0) {
                ((AppConfig_t*)ctx->cfg)->Window.width = strtoll(val, NULL, 10);
                return;
            }
            if (strcmp(key, "height") == 0) {
                ((AppConfig_t*)ctx->cfg)->Window.height = strtoll(val, NULL, 10);
                return;
            }
        }
    }
}

static bool AppConfig_parse_arg(cfg_common_context_t *ctx, int argc, const char **argv, int *index) {
    int i = *index;
    const char *arg = argv[i];
    if (strcmp(arg, "--AppConfig.Window.title") == 0) {
        if (i + 1 < argc) {
            const char *val = argv[++i];
            ((AppConfig_t*)ctx->cfg)->Window.title = cfg_intern_string(ctx, val);
            *index = i; return true;
        }
    }
    if (strncmp(arg, "--AppConfig.Window.title=", 25) == 0) {
        const char *val = arg + 25;
        ((AppConfig_t*)ctx->cfg)->Window.title = cfg_intern_string(ctx, val);
        return true;
    }
    if (strcmp(arg, "--AppConfig.Window.width") == 0) {
        if (i + 1 < argc) {
            const char *val = argv[++i];
            ((AppConfig_t*)ctx->cfg)->Window.width = strtoll(val, NULL, 10);
            *index = i; return true;
        }
    }
    if (strncmp(arg, "--AppConfig.Window.width=", 25) == 0) {
        const char *val = arg + 25;
        ((AppConfig_t*)ctx->cfg)->Window.width = strtoll(val, NULL, 10);
        return true;
    }
    if (strcmp(arg, "--AppConfig.Window.height") == 0) {
        if (i + 1 < argc) {
            const char *val = argv[++i];
            ((AppConfig_t*)ctx->cfg)->Window.height = strtoll(val, NULL, 10);
            *index = i; return true;
        }
    }
    if (strncmp(arg, "--AppConfig.Window.height=", 26) == 0) {
        const char *val = arg + 26;
        ((AppConfig_t*)ctx->cfg)->Window.height = strtoll(val, NULL, 10);
        return true;
    }
    *index = i;
    return false;
}

void AppConfig_parse_cli(AppConfig_t *cfg, int argc, const char **argv) {
    if (!cfg || !argv || argc <= 1) return;
    cfg_common_context_t ctx = { cfg, (cfg_pool_node_t*)cfg->internal_pool };
    for (int i = 1; i < argc; i++) {
        if (argv[i][0] != '-') continue;
        AppConfig_parse_arg(&ctx, argc, argv, &i);
    }
    cfg->internal_pool = ctx.pool;
}

static void AppConfig_ini_handler(void *user, const char *sec, const char *key, const char *val) {
    cfg_common_context_t *ctx = (cfg_common_context_t*)user;
    char sec_copy[256];
    strncpy(sec_copy, sec, sizeof(sec_copy) - 1);
    sec_copy[sizeof(sec_copy) - 1] = '\0';
    char *parts[32]; int num_parts = 0;
    char *s = sec_copy;
    char *token = cfg_next_token(&s, ".");
    while(token && num_parts < 32) { parts[num_parts++] = token; token = cfg_next_token(&s, "."); }

    if (num_parts == 0 || strcmp(parts[0], "AppConfig") != 0) return;
    for (int i = 0; i < num_parts - 1; i++) parts[i] = parts[i+1];
    num_parts--;

    AppConfig_ini_handler_recursive(ctx, key, val, parts, num_parts, 0);
}

cfg_status_t AppConfig_load(AppConfig_t *cfg, const char *filename, int argc, const char **argv, cfg_error_t *err) {
    if (!cfg) return CFG_ERR_VALIDATION;
    memset(cfg, 0, sizeof(AppConfig_t));
    cfg_common_context_t ctx = { cfg, NULL };
    if (err) memset(err, 0, sizeof(cfg_error_t));
    cfg->Window.title = cfg_intern_string(&ctx, "Perlin Noise Map");
    cfg->Window.width = 1024;
    cfg->Window.height = 768;
    if (filename) {
        cfg_status_t status = cfg_parse_ini(filename, AppConfig_ini_handler, &ctx, err);
        if (status != CFG_SUCCESS) { cfg_pool_free(ctx.pool); return status; }
    }
    cfg->internal_pool = ctx.pool;
    AppConfig_parse_cli(cfg, argc, argv);
    if (!AppConfig_validate(cfg, err)) { AppConfig_free(cfg); return CFG_ERR_VALIDATION; }
    return CFG_SUCCESS;
}

void AppConfig_free(AppConfig_t *cfg) {
    if (!cfg) return;
    cfg_pool_free((cfg_pool_node_t*)cfg->internal_pool);
    memset(cfg, 0, sizeof(AppConfig_t));
}

#endif /* CONFIG_IMPLEMENTATION */
